---
title: "Week 4"
author: "Sai"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week4

```{r }
library(tidyverse)

## Determining the type of the data 
typeof(letters)
typeof(1:10)

## Determining the length of the list
x<- list("a","b",1:10)
length(x)

## Logical Vectors

1:10 %% 3 == 0

c(TRUE,TRUE,FALSE,NA)

## Numeric Vectors
typeof(1)
typeof(1L)


## Size of string in bytes
x <- "This is a reasonably long string."
pryr::object_size(x)

y <- rep(x, 1000)
pryr::object_size(y)

## Generating a sample of data and when there is a vector of boolean values then sum of that vector is the number of TRUEs in it and mean is sum of TRUEs by total number of observations
x <- sample(20, 100, replace = TRUE)
y <- x > 10
y
sum(y)  
mean(y)


## If we are running type of on a vector then the complex type is returned as the type of the vector
typeof(c(TRUE, 1L))

## Vector recycling
1:10 + 1:2

## Vector recycling using the functions in tidyverse would require us to recly only scalar values
### Failure scenario
#tibble(x = 1:4, y = 1:2) - failed with an error Error: Tibble columns must have consistent lengths, only values of length one are recycled: * Length 2: Column `y` * Length 4: Column `x`

### Success scenario
tibble(x = 1:4, y = rep(1:2, 2))

## Vector naming - these two ways will let us set names for keys in the vector
set_names(1:3, c("a", "b", "c"))
c(x = 1, y = 2, z = 4)

## Subset

### Subset by Index
x <- c("one", "two", "three", "four", "five")
x[c(3, 2, 5)]

### Subset by logical condition in this case the only values with TRUE will be left in the vector the ones with FALSE will be removed from the vector.

x <- c(10, 3, NA, 5, 8, 1, NA)
x[!is.na(x)]

### Subset by vector key names
x <- c(abc = 1, def = 2, xyz = 5)
x[c("xyz", "def")]


## Lists 
### Ways to define a list
x <- list(1, 2, 3)
x
x_named <- list(a = 1, b = 2, c = 3)
x_named
y <- list("a", 1L, 1.5, TRUE)
y
z <- list(list(1, 2), list(3, 4))
z

## Subsetting in Lists
a <- list(a = 1:3, b = "a string", c = pi, d = list(-1, -5))
### Plucking a value from a list 
str(a[1:2])

### Plucking the value from a nested list
str(a[[1]])

### Extracting named elements of a list
a$a

a[["a"]] ## Both are same in the above case $ is used to pick the named value from the list

## Attributes - Is more like metadata - when I first ran the below chunk of code I got a NULL for the attr(x,"greeting") command but after feeding data for those attributes I could see the value Hi. Even when I print X it shows the values of X which is 1 to 10 and also the attributes attached to it.

### Attributes name implementation
x <- 1:10
attr(x, "greeting")
attr(x, "greeting") <- "Hi!"
attr(x, "Farewell") <- "Bye!"
attributes(x)
x

### Attributes class implementation
as.Date

###List all methods of as.Date
methods("as.Date")

### We can see implementation of this method for each type by using the getS3Method
getS3method("as.Date", "default")
getS3method("as.Date", "numeric")


## Augmented vectors - Built on top of atomic vectors but will have metadata in them including class and they behave differently compared to atomic vectors 
## Factors - Built on top of integers and have levels attribute to them

x <- factor(c("ab", "cd", "ab"), levels = c("ab", "cd", "ef"))
typeof(x)
attributes(x)
## Dates - Numeric vector representing the date from Jan 1 , 1970
x <- as.Date("1971-01-01")
unclass(x)
typeof(x)
attributes(x)


## Dates - POSIXct - Has an optional attribute tzone

x <- lubridate::ymd_hm("1970-01-01 01:00")
unclass(x)

typeof(x)
attributes(x)

attr(x, "tzone") <- "US/Pacific"
x
attr(x, "tzone") <- "US/Eastern"
x

## Dates POSIXit - Built on top of named lists

y <- as.POSIXlt(x)
typeof(y)
attributes(y)

## Tibbles - They have class and names and row.names attributes
## Tibbles behave the same as data.frames because the class of tibble includes data.frames which means its inheriting the behavior.

tb <- tibble::tibble(x = 1:5, y = 5:1)
typeof(tb)
attributes(tb)


df <- data.frame(x = 1:5, y = 5:1)
typeof(df)
attributes(df)

```
```{r}
x <- sample(20, 100, replace = TRUE)
y <- x > 10
y
sum(y)  # how many are greater than 10?
#> [1] 44
mean(y) # what proportion are greater than 10?
#> [1] 0.44
```

