---
title: "Week 5"
author: "Sai Krishna Veerepalli Venkata"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Week 5

```{r }
table1
table2
table3

# All the above datasets represent the same data but for us to perform operations on top of this data it would be better to use a uniform structure which is tidy dataset

# Table 1 data is tidy in the above example as each variable has its own column
# tidyverse packages
# Mutate function
table1 %>% mutate(rate=cases/population * 1000)
# Count number of cases per year
table1 %>% 
  count(year, wt = cases)

# Plot of changes over time
library(ggplot2)
ggplot(table1, aes(year, cases)) + 
  geom_line(aes(group = country), colour = "grey50") + 
  geom_point(aes(colour = country))

# Gather 

table4a

# this table has values as the columns we will use the function gather where key is  the year and value is the value that is distributed across the columns (1999,2000)
table4a %>% 
  gather(`1999`, `2000`, key = "year", value = "cases")

# Similar to above use case where column names are values
table4b %>% 
  gather(`1999`, `2000`, key = "year", value = "population")

# Joining the above two datasets after making them tidy data
tidy4a <- table4a %>% 
  gather(`1999`, `2000`, key = "year", value = "cases")
tidy4b <- table4b %>% 
  gather(`1999`, `2000`, key = "year", value = "population")
left_join(tidy4a, tidy4b)

# Spreading 

table2 # Here the values is distributed across rows so we use spreading to tidy the data
table2 %>%
    spread(key = type, value = count)


# Separate - Pulling one column into multiple columns

table3  # Has rate column that has cases/population
table3 %>% 
  separate(rate, into = c("cases", "population"))  # Separate splits by the first special character

table3 %>% 
  separate(rate, into = c("cases", "population"), sep = "/") # If we wish to use a specific character then we specify it using sep parameter
table3 %>% 
  separate(rate, into = c("cases", "population"), convert = TRUE) # Separate can conver the data types after separation to what makes most sense that can be done by setting convert flag to TRUE

table3 %>% 
  separate(year, into = c("century", "year"), sep = 2) # Separates a year by last two digits

# Unite - Combines multiple columns into one

table5 %>% 
  unite(new, century, year) # By default  unite adds underscore if we dont specify separator parameter
table5 %>% 
  unite(new, century, year, sep = "") # As we dont want any separator for year we are mentioning the parameter as an empty string


# Missing values


stocks <- tibble(
  year   = c(2015, 2015, 2015, 2015, 2016, 2016, 2016),
  qtr    = c(   1,    2,    3,    4,    2,    3,    4),
  return = c(1.88, 0.59, 0.35,   NA, 0.92, 0.17, 2.66)
) 

stocks %>% 
  spread(year, return)

stocks %>% 
  spread(year, return) %>% 
  gather(year, return, `2015`:`2016`, na.rm = TRUE) # Removing not available values
stocks %>% 
  complete(year, qtr)

treatment <- tribble(
  ~ person,           ~ treatment, ~response,
  "Derrick Whitmore", 1,           7,
  NA,                 2,           10,
  NA,                 3,           9,
  "Katherine Burke",  1,           4
)


treatment %>% 
  fill(person)


# Case study

who

who1 <- who %>% 
  gather(new_sp_m014:newrel_f65, key = "key", value = "cases", na.rm = TRUE) # Gathering values from columns and giving a generic name
who1

who1 %>% 
  count(key) # Count the number of values


who2 <- who1 %>% 
  mutate(key = stringr::str_replace(key, "newrel", "new_rel")) # Renaming the column to make it consistent
who2

who3 <- who2 %>% 
  separate(key, c("new", "type", "sexage"), sep = "_") # Splitting the data of the field key by _ and creating three columns out of it
who3

who3 %>% 
  count(new)
who4 <- who3 %>% 
  select(-new, -iso2, -iso3) # Dropping the columns which are constant

who5 <- who4 %>% 
  separate(sexage, c("sex", "age"), sep = 1) # Separate the sexage column into two different columns
who5

# Instea of having 5 different data sets from who to who 5 all these can be computed on the single data set with a series of steps above computed together
who %>%
  gather(key, value, new_sp_m014:newrel_f65, na.rm = TRUE) %>% 
  mutate(key = stringr::str_replace(key, "newrel", "new_rel")) %>%
  separate(key, c("new", "var", "sexage")) %>% 
  select(-new, -iso2, -iso3) %>% 
  separate(sexage, c("sex", "age"), sep = 1)

```